[package]
name = "area_clicker"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
rand = "0.8"
once_cell = "1"
parking_lot = "0.12"
enigo = "0.1"
rdev = { version = "0.5", optional = true }
winit = "0.29"

[features]
hooks = ["rdev"]
